using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.SceneManagement;
using TMPro;
using System;


public class PlayerController : MonoBehaviour
{
    public float speed;
    public TextMeshProUGUI countText;
    public GameObject winTextObject;
    public int item_count;
    private float movementX;
    private float movementY;
    private Rigidbody rb;
    private int count;

    private int total_score;

    //Jumpç³»ã®å‡¦ç†
    public float jump_power = 5.0f;
    private bool isJump = false;

    private bool isCooldown = true;
    //jumpå‡¦ç†

    void Start()
    {
        rb = GetComponent<Rigidbody>();

        count = 0;
        SetCountText();
        winTextObject.SetActive(false);

        total_score = PlayerPrefs.GetInt("TOTAL SCORE", 0);
    }

    void OnMove(InputValue value)
    {
        Vector2 v = value.Get<Vector2>();
        movementX = v.x;
        movementY = v.y;
    }    

    void OnJump()
    {
        if (isCooldown)
        {
            isJump = true;

            isCooldown = false; // Jumpå…¥åŠ›ç„¡åŠ¹

            StartCoroutine(DelayMethod(0.5f, () =>
            {
                // 0.5ç§’å¾Œã«Jumpå…¥åŠ›æœ‰åŠ¹ã«å¾©å¸°
                isCooldown = true;
            }));

        }
    }

    void FixedUpdate()
    {
        Vector3 movement = new Vector3(movementX, 0.0f, movementY);
        rb.AddForce(movement * speed);

        if (isJump)
        {
            // ãƒœãƒ¼ãƒ«ã«åŠ›ã‚’Impulseãƒ¢ãƒ¼ãƒ‰ã§ï¼‹Yè»¸æ–¹å‘ã«ä¸€ç¬åŠ ãˆã‚‹

            // ãƒœãƒ¼ãƒ«ã®ãƒ­ãƒ¼ã‚«ãƒ«åº§æ¨™ç³»Yè»¸ï¼‹æ–¹å‘ã«åŠ›ã‚’åŠ ãˆã‚‹å ´åˆã®ã‚³ãƒ¼ãƒ‰
            // â€»ãƒœãƒ¼ãƒ«è‡ªèº«ã®Yè»¸ã¯ç§»å‹•ã«ã‚ˆã‚Šå›è»¢ã™ã‚‹ã“ã¨ã«æ³¨æ„
            //rb.AddForce(transform.up * jump_power, ForceMode.Impulse);

            //ãƒ¯ãƒ¼ãƒ«ãƒ‰åº§æ¨™ç³»Yè»¸ï¼‹æ–¹å‘ã«åŠ›ã‚’åŠ ãˆã‚‹å ´åˆã®ã‚³ãƒ¼ãƒ‰
            rb.AddForce(Vector3.up * jump_power, ForceMode.Impulse);
            isJump = false;
            //é€£ç¶šã‚¸ãƒ£ãƒ³ãƒ—ã—ãªã„ã‚ˆã†ã«è¨­å®š
        }
    }

    void OnTriggerEnter(Collider other)
    {
        if (other.gameObject.CompareTag("PickUp"))
        {
            //other.gameObject.SetActive(false);
            other.gameObject.GetComponent<Renderer>().enabled = false;

            other.gameObject.GetComponent<BoxCollider>().enabled = false;
            count = count + 1;
            SetCountText();
        }
    }

    void SetCountText()
    {
        countText.text = "Count: " + count.ToString();
        //ï¿½ï¿½ï¿½ï¿½ï¿½Oï¿½ğ•¶ï¿½ï¿½ï¿½Oï¿½É•ÏX
        if (count >= 12)
        {
            winTextObject.SetActive(true);

            // ï¿½ï¿½ï¿½İ‚ÌƒVï¿½[ï¿½ï¿½ï¿½Ôï¿½ï¿½ï¿½ï¿½æ“¾
            int sceneIndex = SceneManager.GetActiveScene().buildIndex;

            StartCoroutine(DelayMethod(5, () =>
            {
                total_score += count;
                PlayerPrefs.SetInt("TOTAL SCORE", total_score);
                PlayerPrefs.Save();
                // ï¿½ï¿½ï¿½ÌƒVï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Ä“Çï¿½ï¿½ï¿½ï¿½ï¿½
                SceneManager.LoadScene(sceneIndex + 1);
            }));
        }
    }

    private IEnumerator DelayMethod(float waitTime, Action action)
    {
        yield return new WaitForSeconds(waitTime);
        action();
    }
}